// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct OrderbookClientProgram;

impl OrderbookClientProgram {
    pub const ROUTE_ID_BOOK: u8 = 1;
}

impl sails_rs::client::Program for OrderbookClientProgram {}

pub trait OrderbookClient {
    type Env: sails_rs::client::GearEnv;
    fn book(&self) -> sails_rs::client::Service<book::BookImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> OrderbookClient
    for sails_rs::client::Actor<OrderbookClientProgram, E>
{
    type Env = E;
    fn book(&self) -> sails_rs::client::Service<book::BookImpl, Self::Env> {
        self.service(OrderbookClientProgram::ROUTE_ID_BOOK)
    }
}
pub trait OrderbookClientCtors {
    type Env: sails_rs::client::GearEnv + sails_rs::client::EnvWithCtor;
    fn create(self)
    -> sails_rs::client::PendingCtor<OrderbookClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv + sails_rs::client::EnvWithCtor> OrderbookClientCtors
    for sails_rs::client::Deployment<OrderbookClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<OrderbookClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> (), 0);
}

pub mod book {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Address(pub H160);
    /// Snapshot returned by the `book` query. Bids are sorted best-first (price desc, id asc),
    /// asks best-first (price asc, id asc).
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct BookView {
        pub seq: u64,
        pub next_id: u64,
        pub bids: Vec<Order>,
        pub asks: Vec<Order>,
        pub recent_fills: Vec<Fill>,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Fill {
        pub seq: u64,
        pub taker: u64,
        pub maker: u64,
        pub price: u64,
        pub qty: u64,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Order {
        pub id: u64,
        pub owner: Address,
        pub side: Side,
        pub price: u64,
        pub qty: u64,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum Side {
        Bid,
        Ask,
    }

    pub trait Book {
        type Env: sails_rs::client::GearEnv;
        /// Full book snapshot. SCALE only: custom DTOs are not ABI-encoded.
        fn book(&self) -> sails_rs::client::PendingCall<io::Book, Self::Env>;
        /// Cancel a resting order. Only the owner may cancel. Returns false if not found or not owned.
        fn cancel(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Cancel, Self::Env>;
        /// Place an order. Matches against the opposite side, rests any remainder. Returns the order id.
        fn place(
            &mut self,
            side: u32,
            price: u64,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::Place, Self::Env>;
        /// Event sequence number reached by the program state.
        fn seq(&self) -> sails_rs::client::PendingCall<io::Seq, Self::Env>;
    }

    pub struct BookImpl;

    impl sails_rs::client::Identifiable for BookImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([146, 176, 42, 185, 38, 237, 139, 124]);
    }

    impl<E: sails_rs::client::GearEnv> Book for sails_rs::client::Service<BookImpl, E> {
        type Env = E;
        fn book(&self) -> sails_rs::client::PendingCall<io::Book, Self::Env> {
            self.pending_call(())
        }
        fn cancel(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Cancel, Self::Env> {
            self.pending_call((id,))
        }
        fn place(
            &mut self,
            side: u32,
            price: u64,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::Place, Self::Env> {
            self.pending_call((side, price, qty))
        }
        fn seq(&self) -> sails_rs::client::PendingCall<io::Seq, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Book () -> super::BookView, 0, <super::BookImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Cancel (id: u64) -> bool, 1, <super::BookImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Place (side: u32, price: u64, qty: u64) -> u64, 2, <super::BookImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Seq () -> u64, 3, <super::BookImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum BookEvents {
            #[codec(index = 0)]
            Cancelled { id: u64, seq: u64 },
            #[codec(index = 1)]
            Filled {
                taker: u64,
                maker: u64,
                seq: u64,
                price: u64,
                qty: u64,
            },
            #[codec(index = 2)]
            Placed {
                id: u64,
                seq: u64,
                owner: Address,
                side: u32,
                price: u64,
                qty: u64,
            },
        }

        impl BookEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Cancelled { .. } => 0,
                    Self::Filled { .. } => 1,
                    Self::Placed { .. } => 2,
                }
            }
        }

        impl sails_rs::client::Event for BookEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for BookEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <BookImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for BookImpl {
            type Event = BookEvents;
        }
    }
}
