export type Order = { id: string; owner: string; side: 'Bid' | 'Ask'; price: string; qty: string };
export type Fill = { seq: string; taker: string; maker: string; price: string; qty: string };
export type BookView = { seq: string; next_id: string; bids: Order[]; asks: Order[]; recent_fills: Fill[] };
export type WriteRecord = {
  n: number;
  path: 'injected' | 'l1';
  label: string;
  submittedAt: number;
  tSubmit: number;
  tPreconf?: number;
  tL1Mined?: number;
  tCommitted?: number;
  wallPreconf?: number;
  wallCommitted?: number;
  orderId?: string;
  ethBlock?: string;
  committedBlock?: string;
  txHash?: string;
  messageId?: string;
  validator?: string;
  error?: string;
  signer?: 'anvil' | 'passkey';
  signerAddress?: string;
  replyError?: string;
  uncommittedByReorg?: number;
};
export type Summary = { count: number; p50: number; p95: number; min: number; max: number } | null;
export type PathStats = {
  excluded: { errored: number; uncommitted: number };
  submitToPreconf: Summary;
  submitToL1Mined: Summary;
  submitToCommitted: Summary;
  preconfToCommitted: Summary;
};
export type Bucket = { t: number; preconf: number; committed: number; p50: number | null };
export type BlockRow = { number: string; hash: string; timestamp: number; txs: number };
export type BlastSummary = { total: number; concurrency: number; senders: number; wallMs: number; preconfPerSec: number; ok: number; failed: number };
export type Snapshot = {
  type: 'snapshot';
  now: number;
  mirror: string;
  sender: string;
  node: { quarantine: number; blockTime: number; startedAt: string };
  ledger: string | null;
  ethHead: string;
  preconf: BookView;
  preconfError: string | null;
  committed: BookView;
  watcher: { headNumber: string; headHash: string; reorgs: number; lastReorgAt?: number; rpcErrors: number };
  totals: { txs: number; preconfirmed: number; committed: number; failed: number; pending: number; allTimeMinMs: number | null; allTimeMeanMs: number | null };
  autopilot: { rate: number; running: boolean };
  validator: { startedAt: number; uptimeSec: number; recycles: number; lastRecycleAt: number | null; recycling: boolean; lastReason: string; recycleEveryMin: number };
  network: { profile: 'local' | 'measured' | 'global'; oneWayMs: number; jitterMs: number; note: string; calibration: { target: string; rttMs: number | null }; profiles: { name: string; oneWayMs: number; note: string }[] };
  latency: { preconf: Summary; e2e: Summary; histogram: { lo: number; hi: number; count: number }[] };
  throughput: { series: Bucket[]; lastSecond: number; peak: number };
  points: { t: number; ms: number; signer: 'anvil' | 'passkey' }[];
  windowSeconds: number;
  fine: { start: number; stepMs: number; counts: number[] };
  blocks: BlockRow[];
  records: WriteRecord[];
  stats: { injected: PathStats; l1: PathStats };
  blast: { running: boolean; last: BlastSummary | null };
};
